version: "3.8"
services:
  client:
    image: midishare/client:release
    build:
      target: production
      args:
        NODE_ENV: production
        SERVER_URL: http://server:3000
        PORT:
        ADDRESS:
        # https://create-react-app.dev/docs/advanced-configuration/
        PUBLIC_URL: https://midishare.app/app/
  nginx:
    ports:
      - "443:443"

  server:
    image: midishare/server:release
    environment:
      NODE_ENV: production
