version: "3.8"

services:
  redis:
    container_name: redis
    init: true
    image: library/redis:6.0
    expose:
      - 6379

  client:
    container_name: client
    init: true
    build:
      context: .
      dockerfile: projects/client/Dockerfile
    environment:
      NODE_ENV:
      PORT: 3000
      ADDRESS: client
      PUBLIC_PATH: /app/
      SERVER_URL:

  server:
    container_name: server
    init: true
    environment:
      REDIS_URL: redis://redis:6379
      BASE_URL:
      SSL_CERT_PATH:
      SSL_KEY_PATH:
      CLIENT_ORIGIN:
    build:
      context: .
      dockerfile: projects/server/Dockerfile

  docs:
    container_name: docs
    init: true
    build:
      context: .
      dockerfile: projects/docs/Dockerfile

  keyboard:
    container_name: keyboard
    init: true
    build:
      context: .
      dockerfile: projects/keyboard/Dockerfile

  common:
    container_name: common
    init: true
    build:
      context: .
      dockerfile: projects/common/Dockerfile
