version: "3.8"
services:
  client:
    build:
      target: production
      args:
        NODE_ENV: production
        SERVER_URL: https://api.midishare.app
        WS_URL: wss://api.midishare.app
        PUBLIC_URL: https://midishare.app
        CDN_URL: https://midishare.b-cdn.net

  server:
    build:
      target: production

  nginx:
    build:
      args:
        API_SERVER_URL: http://127.0.0.1:3000
        API_DOMAIN: api.midishare.app
        WWW_DOMAIN: midishare.app
        SSL_CERT_PATH: /etc/letsencrypt/live/midishare.app/fullchain.pem
        SSL_KEY_PATH: /etc/letsencrypt/live/midishare.app/privkey.pem
        WWW_SERVER_URL: https://midishare.b-cdn.net/
