version: "3.8"

volumes:
  client_parce-cache:
  client_parce-build:
  midishare_keyboard-build:
  midishare_keyboard-parcel-cache:
  midishare_keyboard-parcel-build:
  midishare_inspector-parcel-cache:
  midishare_inspector-parcel-build:

services:
  cdn:
    container_name: cdn
    image: nginx:1.19.6
    ports:
      - "9000:443"
    environment:
      SSL_CERT_PATH: /usr/share/nginx/ssl/localhost.pem
      SSL_KEY_PATH: /usr/share/nginx/ssl/localhost-key.pem
      PUBLIC_PATH: /usr/share/nginx/html
    volumes:
      - "./projects/common/ssl:/usr/share/nginx/ssl:ro"
      - "./projects/common/assets:/usr/share/nginx/html:ro"
      - "./projects/cdn/templates:/etc/nginx/templates:ro"

  client:
    container_name: client
    build:
      target: development
    ports:
      - "3000:3000" # HTTPS
      - "3001:3001" # WS
    environment:
      NODE_ENV: development
      HOST: client
      PORT: 3000
      HMR_PORT: 3001
      CDN_URL: https://localhost:9000
      SERVER_URL: https://localhost:4000
      CACHE_DIR: /parcel-cache
      OUT_DIR: /parcel-build
    volumes:
      - "./projects/client/src:/code/app/src"
      - "./projects/common/ssl:/code/ssl:ro"
      - "./projects/keyboard/src:/code/@midishare/keyboard/src:ro"
      - type: volume
        source: client_parce-cache
        target: /parcel-cache
      - type: volume
        source: client_parce-build
        target: /parcel-build
    command:
      - "--cache-dir=/parcel-cache"
      - "--out-dir=/parcel-build"
      - "--port=3000"
      - "--hmr-port=3001"
      - "--cert=/code/ssl/localhost.pem"
      - "--key=/code/ssl/localhost-key.pem"

  server:
    container_name: server
    env_file: projects/server/.env
    ports:
      - "4000:4000"
    environment:
#      DEBUG: express-openid-connect:*
      ADDRESS: server
      PORT: 4000
      BASE_URL: https://localhost:4000
      SSL_CERT_PATH: /code/app/ssl/localhost.pem
      SSL_KEY_PATH: /code/app/ssl/localhost-key.pem
      CLIENT_URL: https://localhost:3000
    volumes:
      - "./projects/server/src:/code/app/src"
      - "./projects/common/ssl:/code/app/ssl:ro"

  keyboard:
    container_name: keyboard
    init: true
    build:
      context: .
      target: development
      dockerfile: projects/keyboard/Dockerfile
    environment:
      CDN_URL: https://localhost:9000
    volumes:
      - "./projects/keyboard/src:/code/src"
      - "./projects/keyboard/devapp/src:/code/devapp/src"
      - "./projects/common/ssl:/code/ssl:ro"
      - type: volume
        source: midishare_keyboard-parcel-cache
        target: /parcel-cache
      - type: volume
        source: midishare_keyboard-parcel-build
        target: /parcel-build
    ports:
      - "3100:3000" # HTTPS
      - "3101:3001" # WS
    command:
      - "--cache-dir=/parcel-cache"
      - "--out-dir=/parcel-build"
      - "--port=3000"
      - "--hmr-port=3001"
      - "--cert=/code/ssl/localhost.pem"
      - "--key=/code/ssl/localhost-key.pem"

  inspector:
    container_name: inspector
    init: true
    build:
      context: .
      target: development
      dockerfile: projects/inspector/Dockerfile
    volumes:
      - "./projects/inspector/src:/code/src"
      - "./projects/common/ssl:/code/ssl:ro"
      - type: volume
        source: midishare_inspector-parcel-cache
        target: /parcel-cache
      - type: volume
        source: midishare_inspector-parcel-build
        target: /parcel-build
    ports:
      - "3200:3000" # HTTPS
      - "3201:3001" # WS
    command:
      - "--cache-dir=/parcel-cache"
      - "--out-dir=/parcel-build"
      - "--port=3000"
      - "--hmr-port=3001"
      - "--cert=/code/ssl/localhost.pem"
      - "--key=/code/ssl/localhost-key.pem"
