version: "3.8"
services:
  client:
    build:
      target: production
      args:
        NODE_ENV: production
        SERVER_URL: https://api.midishare.app
        WS_URL: ws://api.midishare.app
        PUBLIC_URL: https://midishare.app
        CDN_URL: https://midishare.b-cdn.net

  server-app:
    build:
      target: production
    environment:
      ADDRESS: 127.0.0.1
      PORT: 443
      BASE_URL: https://api.midishare.app
      CLIENT_URL: https://midishare.app
