version: "3.8"
services:
  client:
    build:
      target: production
      args:
        NODE_ENV: production
        SERVER_URL: https://api.midishare.app
        WS_URL: wss://api.midishare.app
        PUBLIC_URL: https://www.midishare.app
        PUBLIC_CDN_URL: https://midishare.b-cdn.net
        STATIC_CDN_URL: https://midishare-static.b-cdn.net

  server:
    build:
      target: production

#  server_nodejs:
#    build:
#      target: production
