version: "3.8"
services:
  client:
    build:
      target: production
      args:
        NODE_ENV: production
        SERVER_URL: https://api.midishare.app
        WS_URL: ws://api.midishare.app
        PUBLIC_URL: https://midishare.app
        CDN_URL: https://midishare.b-cdn.net

  server:
    build:
      target: production

  nginx:
    build:
      args:
        SERVER_URL: http://127.0.0.1:4100
        SERVER_NAME: api.midishare.app
        SSL_CERT_PATH: /ssl/localhost.pem
        SSL_KEY_PATH: /ssl/localhost-key.pem
