version: "3.8"

services:
  client:
    container_name: client
    init: true
    build:
      context: .
      dockerfile: projects/client/Dockerfile
    environment:
      NODE_ENV:
      SERVER_URL:

  server-app:
    container_name: server
    init: true
    environment:
      BASE_URL:
      SSL_CERT_PATH:
      SSL_KEY_PATH:
      CLIENT_ORIGIN:
      SQLITE_DATABASE: /db/database.db
      DB_MIGRATIONS_PATH: /db/migrations
    volumes:
      - "./db:/db"
    build:
      context: .
      dockerfile: projects/server-app/Dockerfile

  docs:
    container_name: docs
    init: true
    build:
      context: .
      dockerfile: projects/docs/Dockerfile

  keyboard:
    container_name: keyboard
    init: true
    build:
      context: .
      dockerfile: projects/keyboard/Dockerfile

  common:
    container_name: common
    init: true
    build:
      context: .
      dockerfile: projects/common/Dockerfile
