version: "3.8"

volumes:
  client_parcel-cache:
  docs_parcel-cache:
  inspector_parcel-cache:

services:
  cdn:
    container_name: cdn
    image: nginx:1.19.6
    ports:
      - "9000:443"
    environment:
      SSL_CERT_PATH: /usr/share/nginx/ssl/localhost.pem
      SSL_KEY_PATH: /usr/share/nginx/ssl/localhost-key.pem
      PUBLIC_PATH: /usr/share/nginx/html
    volumes:
      - "./ssl:/usr/share/nginx/ssl:ro"
      - "./assets:/usr/share/nginx/html:ro"
      - "./projects/cdn/templates:/etc/nginx/templates:ro"

  client:
    build:
      target: development
    ports:
      - "3000:3000" # HTTPS
      - "3001:3001" # WS
    environment:
      NODE_ENV: development
      HOST: client
      PORT: 3000
      HMR_PORT: 3001
      CDN_URL: https://localhost:9000
      SERVER_URL: https://localhost:4000
      WS_URL: ws://localhost:4000
    volumes:
      - "./ssl:/ssl:ro"
      - "./projects/client/src:/code/app/src"
      - "./projects/keyboard/dist:/code/keyboard/dist:ro"
      - "./projects/common/dist:/code/common/dist:ro"
      - type: volume
        source: client_parcel-cache
        target: /parcel-cache
    command:
      - "--cache-dir=/parcel-cache"
      - "--port=3000"
      - "--hmr-port=3001"
      - "--cert=/ssl/localhost.pem"
      - "--key=/ssl/localhost-key.pem"

  docs:
    build:
      target: development
    ports:
      - "3100:3000"
      - "3101:3001"
    environment:
      NODE_ENV: development
      CDN_URL: https://localhost:9000
    volumes:
      - "./ssl:/ssl:ro"
      - "./projects/docs/src:/code/app/src"
      - "./projects/keyboard/dist:/code/keyboard/dist:ro"
      - type: volume
        source: docs_parcel-cache
        target: /parcel-cache
    command:
      - "--cache-dir=/parcel-cache"
      - "--port=3000"
      - "--hmr-port=3001"
      - "--cert=/ssl/localhost.pem"
      - "--key=/ssl/localhost-key.pem"

  server:
    container_name: server
    env_file: projects/server/.env
    ports:
      - "4000:4000"
    environment:
      ADDRESS: server
      PORT: 4000
      BASE_URL: https://localhost:4000
      SSL_CERT_PATH: /ssl/localhost.pem
      SSL_KEY_PATH: /ssl/localhost-key.pem
      CLIENT_URL: https://localhost:3000
    volumes:
      - "./ssl:/ssl:ro"
      - "./projects/server/src:/code/app/src"
      - "./projects/common/dist:/code/common/dist:ro"

  keyboard:
    build:
      target: development
    volumes:
      - "./projects/keyboard/src:/code/app/src"
      - "./projects/keyboard/dist:/code/app/dist"
    command:
      - "--watch"

  common:
    build:
      target: development
    volumes:
      - "./projects/common/src:/code/app/src"
      - "./projects/common/dist:/code/app/dist"
    command:
      - "--watch"

  inspector:
    container_name: inspector
    init: true
    build:
      context: .
      target: development
      dockerfile: projects/inspector/Dockerfile
    volumes:
      - "./ssl:/ssl:ro"
      - "./projects/inspector/src:/code/src"
      - type: volume
        source: inspector_parcel-cache
        target: /parcel-cache
    ports:
      - "3200:3000" # HTTPS
      - "3201:3001" # WS
    command:
      - "--cache-dir=/parcel-cache"
      - "--port=3000"
      - "--hmr-port=3001"
      - "--cert=/ssl/localhost.pem"
      - "--key=/ssl/localhost-key.pem"
