version: "3.8"

services:
  client:
    container_name: client
    init: true
    build:
      context: .
      dockerfile: projects/client/Dockerfile
    environment:
      NODE_ENV:
      PORT: 3000
      ADDRESS: client
      PUBLIC_PATH: /app/
      SERVER_URL: http://server:3000

  server:
    container_name: server
    init: true
    build:
      context: .
      dockerfile: projects/server/Dockerfile
