server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://22185:eyJrIjoiYWI4ZjVjZjc1YzgxOTQ3MzJkNGY2YjU1OTdjNThkMjQxOWNkZDk4ZCIsIm4iOiJyb290QG1pZGlzaGFyZS5hcHAiLCJpZCI6NDY2MjM1fQ==@logs-prod-us-central1.grafana.net/api/prom/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_access_log
          agent: promtail
          host: midishare
          __path__: /var/log/nginx/promtail-access.log
